const KEY="pulseRiftSaveV2";const D=["Easy","Normal","Hard","Harder","Insane","Extreme"];
const N=["Riftborn","Pulse Factory","Neon District","Voltage","Overdrive","Gravity Zero","Night Run","Hyperlane","Skyline","Digital Depth","Crystal Core","Turbo Tunnel","Arc Reactor","Moonbase","Starfall","Inferno Gate","Quantum Lab","Ghost Circuit","Prism Peak","Omega Road","Cyber Temple","Final Horizon","Afterburn","Infinity"];
const desc=["Warm-up néon","Usine rythmée","Course cyberpunk","Haute tension","Vitesse maximale","Gravité instable","Course nocturne","Hyper vitesse","Toits futuristes","Descente digitale","Cristaux et pièges","Tunnel turbo","Réacteur","Base lunaire","Pluie d'étoiles","Portail de lave","Laboratoire","Circuit spectral","Sommet prismatique","Route Omega","Temple cyber","Horizon final","Après-burner","Route infinie"];
const dc=["#49e8ff","#70ff88","#ffd35b","#ff9652","#ff5c92","#a875ff"];
const skins=["Pulse","Volt","Nova","Plasma","Aurora","Inferno","Void","Prism","Cyber","Neon","Solar","Lunar","Frost","Toxic","Comet","Quantum","Rift","Glitch","Titan","Vortex","Phantom","Apex","Spectra","Storm","Flux","Orbit","Pixel","Hyper","Zenith","Chrome","Blaze","Eclipse","Cosmo","Matrix","Infernal","Crystal","Turbo","Vector","Omega","Arc","Rift-X","Rift-Z"].map((n,i)=>({name:n,id:i,price:i<3?0:65+i*30,c:[dc[i%6],dc[(i+2)%6]],rarity:i<8?"Rare":i<20?"Epic":i<34?"Legendary":"Mythic"}));
const trailNames=["Basic","Spark","Comet","Rainbow","Plasma","Stars","Smoke","Lightning","Fire","Void","Pixel","Aurora","Prism","Meteor","Glitch","Neon","Quantum","Crystal","Inferno","Solar","Toxic","Frost","Galaxy","Pulse","Nova","Rift","Storm","Hyper","Chrome","Spectral","Eclipse","Omega"];
const trails=trailNames.map((n,i)=>({name:n,id:i,price:i?45+i*18:0,c:[dc[(i+1)%6],dc[(i+4)%6]]}));
const ach=[["first","Premier Rift","Finir une map"],["ten","10 victoires","Finir 10 maps"],["hard","Hard Runner","Finir une map Hard+"],["extreme","Extrême","Finir une map Extreme"],["racer","Racer","Gagner une course"],["coins","Collectionneur","100 pièces"],["shop","Client","Acheter en boutique"],["fashion","Fashion","Débloquer 10 skins"],["marathon","Marathon","30 parties"],["perfect","Perfect Run","Finir sans mort"]];
const levels=N.map((name,i)=>({id:i,name,desc:desc[i],difficulty:D[Math.min(5,Math.floor(i/4))],length:70+i*4,speed:4.3+(i%6)*.28,color:[dc[i%6],dc[(i+3)%6]],coins:10+(i%6)*3}));
function fresh(){return{coins:300,user:"Player",skin:0,trail:0,ownedSkins:[0,1,2],ownedTrails:[0],best:{},stats:{plays:0,wins:0,deaths:0,coins:0,score:0,time:0},ach:{},streak:0,lastDaily:"",shopDay:"",shop:[],bought:[],scores:[],settings:{music:70,sfx:80,particles:true,shake:true,performance:false,showFps:false}}}
let S=JSON.parse(localStorage.getItem(KEY)||"null")||fresh();const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function seed(){const d=new Date();return d.getUTCFullYear()*10000+(d.getUTCMonth()+1)*100+d.getUTCDate()}function rnd(s){let x=Math.sin(s)*10000;return()=>{x=Math.sin(x)*10000;return x-Math.floor(x)}}function day(){return seed()%levels.length}
function shopInit(){if(S.shopDay!==String(seed())){const r=rnd(seed());S.shopDay=String(seed());S.shop=[];for(let i=0;i<6;i++)S.shop.push({type:i%2?"trail":"skin",id:i%2?1+Math.floor(r()*31):3+Math.floor(r()*39),off:20+(i*7)%36});S.bought=[];save()}}
function view(id){if(id!=="game"&&window.G?.running)G.stop();$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id));render()}
$$("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#coinsBtn").onclick=()=>view("shop");$("#diff").onchange=renderLevels;$("#sort").onchange=renderLevels;
function renderLevels(){let a=[...levels],f=$("#diff").value;if(f!=="all")a=a.filter(x=>x.difficulty===f);if($("#sort").value==="diff")a.sort((x,y)=>D.indexOf(x.difficulty)-D.indexOf(y.difficulty));if($("#sort").value==="best")a.sort((x,y)=>(S.best[y.id]?.pct||0)-(S.best[x.id]?.pct||0));$("#levelGrid").innerHTML=a.map(l=>`<article class="level-card"><div class="level-art" style="--a:${l.color[0]};--b:${l.color[1]}"></div><span class="tag">${l.difficulty}</span><h3>${l.id+1}. ${l.name}</h3><p>${l.desc}</p><div class="meta"><span>⚡${l.speed.toFixed(1)}</span><span>◈${l.coins}</span><span>${S.best[l.id]?.pct||0}%</span></div><button class="primary" onclick="start(${l.id},'classic')">JOUER</button></article>`).join("")}
function renderCos(){let sk=skins[S.skin],tr=trails[S.trail];$("#preview").style.background=`linear-gradient(135deg,${sk.c[0]},${sk.c[1]})`;$("#skinName").textContent=sk.name;$("#trailName").textContent="Trail : "+tr.name;$("#loadoutInfo").textContent=sk.rarity+" • équipement sauvegardé";$("#skinTab").innerHTML=skins.map(x=>`<div class="cos-card ${S.ownedSkins.includes(x.id)?"owned":""}"><div class="cos-icon" style="background:linear-gradient(135deg,${x.c[0]},${x.c[1]})">◆</div><h4>${x.name}</h4><p>${x.rarity}</p><button onclick="equip('skin',${x.id})">${S.skin===x.id?"ÉQUIPÉ":S.ownedSkins.includes(x.id)?"ÉQUIPER":x.price+" ◈"}</button></div>`).join("");$("#trailTab").innerHTML=trails.map(x=>`<div class="cos-card ${S.ownedTrails.includes(x.id)?"owned":""}"><div class="cos-icon" style="background:linear-gradient(135deg,${x.c[0]},${x.c[1]})">✦</div><h4>${x.name}</h4><p>Trail animé</p><button onclick="equip('trail',${x.id})">${S.trail===x.id?"ÉQUIPÉ":S.ownedTrails.includes(x.id)?"ÉQUIPER":x.price+" ◈"}</button></div>`).join("")}
function equip(type,id){let arr=type==="skin"?S.ownedSkins:S.ownedTrails,obj=type==="skin"?skins[id]:trails[id];if(!arr.includes(id)){if(S.coins<obj.price)return alert("Pas assez de pièces.");S.coins-=obj.price;arr.push(id);S.ach.shop=true}else type==="skin"?S.skin=id:S.trail=id;save();render()}
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#skinTab").classList.toggle("hidden",b.dataset.tab!=="skinTab");$("#trailTab").classList.toggle("hidden",b.dataset.tab!=="trailTab")});
function renderShop(){shopInit();$("#shopGrid").innerHTML=S.shop.map((x,i)=>{let o=x.type==="skin"?skins[x.id]:trails[x.id],p=Math.max(1,Math.floor(o.price*(1-x.off/100))),b=S.bought.includes(i);return`<div class="shop-card cos-card"><div class="cos-icon" style="background:linear-gradient(135deg,${o.c[0]},${o.c[1]})">${x.type==="skin"?"◆":"✦"}</div><span class="tag">-${x.off}%</span><h4>${o.name}</h4><p>${o.price} → ${p} ◈</p><button ${b?"disabled":""} onclick="buy(${i})">${b?"ACHETÉ":p+" ◈"}</button></div>`}).join("")}
function buy(i){let x=S.shop[i],o=x.type==="skin"?skins[x.id]:trails[x.id],p=Math.max(1,Math.floor(o.price*(1-x.off/100)));if(S.coins<p)return alert("Pas assez de pièces.");S.coins-=p;let a=x.type==="skin"?S.ownedSkins:S.ownedTrails;if(!a.includes(x.id))a.push(x.id);S.bought.push(i);S.ach.shop=true;save();render()}
function renderDaily(){let l=levels[day()];$("#dailyName").textContent=l.name;$("#dailyDesc").textContent=l.desc+" • objectif : terminer.";$("#dailyDiff").textContent=l.difficulty;$("#dailyReward").textContent=150+l.id*10;$("#dailyPlay").onclick=()=>start(l.id,"daily");$("#streak").innerHTML=[1,3,7,14,30].map(n=>`<div class="reward">🔥 ${n}<br><small>${n*50} ◈</small></div>`).join("")}
function renderProfile(){let rank=S.stats.wins<3?"Rookie":S.stats.wins<10?"Runner":S.stats.wins<25?"Pro":S.stats.wins<50?"Master":"Legend";$("#username").value=S.user;$("#rank").textContent=`Rang ${rank} • ${S.stats.wins} victoires`;$("#avatar").style.background=`linear-gradient(135deg,${skins[S.skin].c[0]},${skins[S.skin].c[1]})`;$("#miniAvatar").style.background=`linear-gradient(135deg,${skins[S.skin].c[0]},${skins[S.skin].c[1]})`;$("#stats").innerHTML=[["Parties",S.stats.plays],["Victoires",S.stats.wins],["Morts",S.stats.deaths],["Pièces",S.stats.coins],["Score",S.stats.score],["Temps",Math.floor(S.stats.time)+"s"]].map(x=>`<div class="stat"><b>${x[1]}</b><small>${x[0]}</small></div>`).join("");$("#achievements").innerHTML=ach.map(a=>`<div class="achievement ${S.ach[a[0]]?"":"locked"}"><b>${S.ach[a[0]]?"✓":"◇"} ${a[1]}</b><small>${a[2]}</small></div>`).join("")}
function renderBoard(){let r=[...S.scores].sort((a,b)=>b.score-a.score).slice(0,20);if(!r.length)r=[{name:S.user,score:0,pct:0}];$("#board").innerHTML=r.map((x,i)=>`<div class="leader-row"><b>#${i+1}</b><strong>${x.name}</strong><span>${x.score}</span><span>${x.pct}%</span></div>`).join("")}
function render(){shopInit();$("#coins").textContent=S.coins;$("#homeBest").textContent=Math.max(0,...Object.values(S.best).map(x=>x.pct||0))+"%";$("#homeSkins").textContent=skins.length;$("#homeTrails").textContent=trails.length;renderLevels();renderCos();renderShop();renderDaily();renderProfile();renderBoard()}
$("#username").onchange=e=>{S.user=e.target.value.trim().slice(0,16)||"Player";save()};$("#reset").onclick=()=>{if(confirm("Effacer toute la progression ?")){S=fresh();save();render()}};
$("#botRace").onclick=()=>start(day(),"race");$("#onlineRace").onclick=()=>alert("Le serveur WebSocket est fourni dans /server. Configure l'URL du serveur dans js/online.js pour activer le matchmaking Internet.");
$("#register").onclick=()=>alert("Pour les comptes sécurisés, démarre le serveur fourni dans /server puis configure son URL.");$("#login").onclick=()=>alert("Connexion en ligne disponible via le backend fourni.");$("#logout").onclick=()=>alert("Déconnexion locale : la progression locale reste disponible.");
for(const k of ["music","sfx","particles","shake","performance","showFps"]){const e=$("#"+k);e.oninput=()=>{S.settings[k]=e.type==="checkbox"?e.checked:+e.value;save()};if(e.type==="checkbox")e.checked=S.settings[k];else e.value=S.settings[k]}
window.start=(id,mode)=>{G.start(levels[id],mode);view("game")};