const c=document.querySelector("#canvas"),x=c.getContext("2d");
const G={running:false,paused:false,over:false,l:null,mode:"classic",p:null,obs:[],parts:[],t:0,coins:0,score:0,last:0,startTime:0,
resize(){let d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=(innerHeight-64)*d;x.setTransform(d,0,0,d,0,0)},
start(l,m){this.resize();this.l=l;this.mode=m;this.running=true;this.paused=false;this.over=false;this.t=0;this.coins=0;this.score=0;this.startTime=performance.now();this.last=performance.now();this.p={x:115,y:0,vy:0,r:18,ground:false};this.obs=[];this.parts=[];let R=(s=>{let z=Math.sin(s)*9999;return()=>{z=Math.sin(z)*9999;return z-Math.floor(z)}})(l.id*77+new Date().getDate());for(let q=450;q<l.length*105;q+=125+R()*110){let h=28+R()*60;this.obs.push({x:q,w:24+R()*24,h,kind:R()<.78?"spike":"block"});if(R()<.55)this.obs.push({x:q+42,y:-55-R()*50,w:14,h:14,kind:"coin"})}requestAnimationFrame(tick)},
stop(){this.running=false},jump(){if(this.running&&!this.paused&&!this.over&&this.p.ground){this.p.vy=-12.3;this.p.ground=false;burst(this.p.x,this.p.y,"jump")}},
pause(){if(!this.running||this.over)return;this.paused=!this.paused;$("#overlay").classList.toggle("hidden",!this.paused);$("#ovtitle").textContent="PAUSE";$("#ovey").textContent="PAUSE";$("#ovtext").textContent="";$("#ovmain").textContent="REPRENDRE"},
update(dt){if(this.paused||this.over)return;let p=this.p,g=innerHeight-116;p.vy+=.64*dt;p.y+=p.vy*dt;if(p.y>g-p.r){p.y=g-p.r;p.vy=0;p.ground=true}let sp=this.l.speed*dt;this.t+=sp;this.obs.forEach(o=>o.x-=sp);this.obs=this.obs.filter(o=>o.x>-80);if(this.obs.some(o=>o.kind==="spike"&&o.x<p.x+p.r&&o.x+o.w>p.x-p.r&&p.y+p.r>g-o.h))return this.die();this.obs=this.obs.filter(o=>{if(o.kind==="coin"&&o.x<p.x+p.r&&o.x+o.w>p.x-p.r&&Math.abs((g+o.y)-p.y)<35){this.coins++;S.stats.coins++;burst(o.x,p.y,"coin");return false}return true});this.score=Math.floor(this.t+this.coins*75);if(this.t>this.l.length*100)this.win();else if(Math.random()<.4)burst(p.x-18,p.y+8,"trail")},
die(){S.stats.deaths++;this.over=true;burst(this.p.x,this.p.y,"death");if(S.settings.shake)c.animate([{transform:"translate(6px)"},{transform:"translate(-6px)"},{transform:"translate(3px)"},{transform:"translate(0)"}],{duration:160});this.end(false)},
win(){if(this.over)return;this.over=true;S.stats.wins++;S.stats.score+=this.score;S.stats.time+=(performance.now()-this.startTime)/1000;S.ach.first=true;if(["Hard","Harder","Insane","Extreme"].includes(this.l.difficulty))S.ach.hard=true;if(this.l.difficulty==="Extreme")S.ach.extreme=true;if(this.mode==="race")S.ach.racer=true;if(S.stats.coins>=100)S.ach.coins=true;if(S.stats.wins>=10)S.ach.ten=true;if(S.stats.wins>=30)S.ach.marathon=true;if(S.ownedSkins.length>=10)S.ach.fashion=true;S.best[this.l.id]={pct:100,score:Math.max(this.score,S.best[this.l.id]?.score||0)};S.scores.push({name:S.user,score:this.score,pct:100});S.coins+=120+this.l.id*8;if(this.mode==="daily"&&S.lastDaily!==String(seed())){S.coins+=150+this.l.id*10;S.streak++;S.lastDaily=String(seed())}save();this.end(true)},
end(win){$("#overlay").classList.remove("hidden");$("#ovey").textContent=win?"RIFT CLEARED":"CRASH";$("#ovtitle").textContent=win?"VICTORY":"TRY AGAIN";$("#ovtext").textContent=win?`+${120+this.l.id*8} ◈ • Score ${this.score}`:"Ton run est terminé. Repars immédiatement.";$("#ovmain").textContent=win?"REJOUER":"RESTART"},
draw(){let w=innerWidth,h=innerHeight-64,g=h-55,l=this.l;let q=x.createLinearGradient(0,0,w,h);q.addColorStop(0,"#050716");q.addColorStop(1,l.color[1]+"38");x.fillStyle=q;x.fillRect(0,0,w,h);for(let i=0;i<35;i++){x.fillStyle=l.color[0]+(i%3?"12":"25");x.fillRect((i*91-this.t*.25)%w,(i*47)%h,2,2)}x.fillStyle="#11172f";x.fillRect(0,g,w,h-g);for(let xx=-(this.t%60);xx<w;xx+=60){x.fillStyle=l.color[0]+"45";x.fillRect(xx,g,1,h-g)}this.obs.forEach(o=>{if(o.kind==="coin"){x.beginPath();x.arc(o.x,g+o.y,7,0,Math.PI*2);x.fillStyle="#ffd45c";x.fill();x.strokeStyle="#fff5a0";x.stroke()}else{ x.fillStyle=o.kind==="spike"?l.color[0]:l.color[1];x.beginPath();x.moveTo(o.x,g);x.lineTo(o.x+o.w/2,g-o.h);x.lineTo(o.x+o.w,g);x.closePath();x.fill()}});let sk=skins[S.skin];x.save();x.translate(this.p.x,this.p.y);x.rotate(this.t/100);x.shadowBlur=22;x.shadowColor=sk.c[0];x.fillStyle=sk.c[0];x.fillRect(-18,-18,36,36);x.fillStyle=sk.c[1];x.fillRect(-7,-7,14,14);x.restore();this.parts.forEach(p=>{x.globalAlpha=p.a;x.fillStyle=p.c;x.fillRect(p.x,p.y,3,3)});x.globalAlpha=1},
hud(){let p=Math.min(100,Math.floor(this.t/(this.l.length*100)*100));$("#gname").textContent=this.l.name;$("#gmode").textContent=this.mode.toUpperCase();$("#bar").style.width=p+"%";$("#pct").textContent=p+"%";$("#gcoins").textContent=this.coins}}
function burst(px,py,type){if(!S.settings.particles)return;let co=type==="coin"?"#ffd45c":skins[S.skin].c[0],n=type==="death"?38:12;for(let i=0;i<n;i++)G.parts.push({x:px,y:py,a:1,c:co,vx:(Math.random()-.5)*6,vy:(Math.random()-.5)*6})}
function tick(now){if(!G.running)return;let dt=Math.min(2,(now-G.last)/16.67);G.last=now;G.update(dt);G.parts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.1;p.a-=.035});G.parts=G.parts.filter(p=>p.a>0);G.draw();G.hud();requestAnimationFrame(tick)}
addEventListener("resize",()=>G.resize());addEventListener("keydown",e=>{if(["Space","ArrowUp","KeyW"].includes(e.code)){e.preventDefault();G.jump()}if(e.code==="Escape")G.pause()});c.addEventListener("pointerdown",()=>G.jump());$("#jump").addEventListener("pointerdown",e=>{e.preventDefault();G.jump()});$("#pause").onclick=()=>G.pause();$("#ovmain").onclick=()=>{if(G.over)G.start(G.l,G.mode);else G.pause()};$("#ovrestart").onclick=()=>G.start(G.l,G.mode);$("#ovexit").onclick=()=>view("levels");